import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Header from "../components/Header/Header.component";
import Footer from "../components/Footer/Footer.component";
import Silder from "./slider";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Header></Header>
      </header>

      <main className={styles.main}>
        <Silder></Silder>
      </main>

      <footer className={styles.footer}>
        <Footer></Footer>
      </footer>
    </div>
  );
};

export default Home;
